---
- hosts: eap
  
  tasks: 

    - set_fact:
        ips_list: "{{ groups['eap'| map('extract', hostvars,'ansible_host')| list }}"
        
#   # msg is constructed from inventory group 'redis'
#     - debug:
#         msg: "{{ ips_list  | join(',') }}"
#       vars:
#  #       eap_nodes: "{{ ansible_host }}"
#         eap_port: 7600
#         ips_list: {{ groups['eap'| map('extract', hostvars,'ansible_host')| list }}
    

    - debug:
        msg: "{{ ips_lists }}"