---
- hosts: "*eap"
  
  tasks: 

  # msg is constructed from inventory group 'redis'
    - debug:
        msg: "{{ ips_list | join(',') }}"
      vars:
 #       eap_nodes: "{{ ansible_host }}"
        eap_port: 7600
        ips_list: "{{ hostvars | map(attribute='ansible_host') | list }}"