---
- name: Deploy {{ rhv_environment }} environment on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    rhv_environment: dev

  tasks:

    - name: Deploy Linux Web Apps Instances
      include_role:
        name: nehrman.ansible-role-rhv
        tasks_from: main.yml
      vars:
        rhv_vmname: "{{ customer }}-weblx0{{ item }}.openhybridcloud.io"
        rhv_vm_nic: 'eth0'
        rhv_vm_nic_prof: 'no_filter'
        rhv_vm_username: 'centos'
        rhv_vm_pwd: 'password'
        rhv_vm_ip: '147.135.178.12{{ item }}'
        rhv_vm_gw: '147.135.178.112'
        rhv_vm_subnet: '255.255.255.240'
        rhv_vm_nic_onboot: true
        rhv_vm_comment: 'web'
        rhv_vm_dns_ip: '5.39.49.68'
        rhv_vm_dns_search: 'openhybridcloud.io'
      with_sequence: count="{{ rhv_lx_web_count }}"
