---
- name: Deploy {{ rhv_environment }} environment on RHV
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    rhv_environment: dev

  tasks:

    - name: Deploy Linux Web Apps Instances
      include_role:
        name: nehrman.ansible-role-azure
        tasks_from: create_lin_web.yml
      vars:
        instance_name: "weblx0{{ item }}"
        instance_role: "web"
        instance_ansible_port: "22"
        instance_ansible_user: "testuser"
        az_os_type_vm: "Linux"
        az_image_offer: "CentOS"
        az_image_publisher: "OpenLogic"
        az_image_sku: "7.3"
        az_ssh_pwd_enabled: "true"
      with_sequence: count="{{ az_lx_web_count }}"
