---
- name: Add Nodes to Load Balancer
  hosts: "{{ scope }}"
  connection: local

  tasks:

    - name: Ensure Nodes are present in F5 Load Balancer
      include_role:
        name: nehrman.ansible-role-f5
        tasks_from: add_apps_to_f5
         
